 name: Deploy to GitHub Pages via angular-cli-ghpages

 on: [push]

 jobs:
   build-and-deploy:
     runs-on: ubuntu-latest

     steps:
     - name: Checkout
       uses: actions/checkout@v2

     - name: Use Node.js 10.x
       uses: actions/setup-node@v1
       with:
         node-version: 10.x

     - name: Prepare and deploy
       env:
         GH_TOKEN: ${{ secrets.GH_TOKEN }}
       run: |
         npm install

         ###
         # Configure Angular first!
         
         # npm run webdriver-update-ci

         ####
         npm run ng deploy --base-href=/walktojerusalem/ --name="jackcooper04" --email=jack@acooper.net
